CREATE TABLE IF NOT EXISTS ai_ingestion_records (
  id INT AUTO_INCREMENT PRIMARY KEY,
  source_module VARCHAR(50) NOT NULL DEFAULT 'ai_video',
  ai_provider VARCHAR(50) DEFAULT NULL,
  original_file_name VARCHAR(255) NOT NULL,
  stored_file_name VARCHAR(255) DEFAULT NULL,
  file_path TEXT DEFAULT NULL,
  file_url TEXT DEFAULT NULL,
  mime_type VARCHAR(100) DEFAULT NULL,
  file_size BIGINT DEFAULT NULL,
  external_file_id VARCHAR(255) DEFAULT NULL,
  external_file_uri TEXT DEFAULT NULL,
  extracted_text LONGTEXT DEFAULT NULL,
  processing_status VARCHAR(30) NOT NULL DEFAULT 'pending',
  review_status VARCHAR(30) NOT NULL DEFAULT 'pending',
  review_note TEXT DEFAULT NULL,
  error_message TEXT DEFAULT NULL,
  created_by_user_id INT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_source_module (source_module),
  INDEX idx_processing_status (processing_status),
  INDEX idx_review_status (review_status),
  INDEX idx_created_by_user_id (created_by_user_id),
  INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
